#!/bin/bash

# Auto-generated script to execute Phase 01 - Discovery
# Generated by Phase 00 on 20260120T103556Z

set -euo pipefail

# Configuration
RUN_ID="maestro_20260120T103556Z"
CONFIG_FILE="/Users/aamirraza/asr/maestro-v1/artifacts/processed/discovery_config_maestro_20260120T103556Z.json"
PHASE_01_SCRIPT="/Users/aamirraza/asr/maestro-v1/01-discover/run-discovery.sh"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}  Maestro Phase 01 - Discovery${NC}"
echo -e "${CYAN}  Run ID: ${RUN_ID}${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo

# Check if discovery script exists
if [[ ! -f "$PHASE_01_SCRIPT" ]]; then
    echo "Error: Phase 01 script not found at: $PHASE_01_SCRIPT"
    exit 1
fi

# Check if config file exists
if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "Error: Discovery config not found at: $CONFIG_FILE"
    exit 1
fi

echo -e "${GREEN}Starting discovery process...${NC}"
echo

# Execute Phase 01
exec "$PHASE_01_SCRIPT" \
    --config "$CONFIG_FILE" \
    --run-id "$RUN_ID" \
    --verbose
