apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    compliance.eazyops.com/pci-dss: "true"
    platform.eazyops.com/environment: prod
    platform.eazyops.com/tenant-code: beta
  name: computenetwork-beta-prod
  namespace: t-beta-prod
spec:
  autoCreateSubnetworks: false
  deleteDefaultRoutesOnCreate: false

---

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    compliance.eazyops.com/pci-dss: "true"
    platform.eazyops.com/environment: prod
    platform.eazyops.com/tenant-code: beta
  name: computenetwork-beta-prod
  namespace: t-beta-prod
spec:
  autoCreateSubnetworks: false
  deleteDefaultRoutesOnCreate: false

---

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    compliance.eazyops.com/pci-dss: "true"
    platform.eazyops.com/environment: prod
    platform.eazyops.com/tenant-code: beta
  name: computenetwork-beta-prod
  namespace: t-beta-prod
spec:
  autoCreateSubnetworks: false
  deleteDefaultRoutesOnCreate: true
  privateClusterConfig:
    enablePrivateEndpoint: true
  privateIpGoogleAccess: true

---

